nohup: ignoring input
加载数据...
Time usage: 0:00:03
Some weights of the model checkpoint at ./bert_pretrain were not used when initializing BertModel: ['cls.predictions.transform.dense.weight', 'cls.seq_relationship.bias', 'cls.predictions.bias', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.seq_relationship.weight', 'cls.predictions.decoder.weight', 'cls.predictions.transform.LayerNorm.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
7,177,157 total parameters.
Epoch [1/3]
Traceback (most recent call last):
  File "/home/huyiwen/KnowledgeDistillation/distill.py", line 59, in <module>
    student_train(T_model, S_model, cfg, train_loader, test_loader)
  File "/home/huyiwen/KnowledgeDistillation/student.py", line 54, in student_train
    s_logits = S_model(texts)
  File "/home/huyiwen/anaconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/huyiwen/KnowledgeDistillation/models/biLSTM.py", line 64, in forward
    lstm_out, hidden = self.lstm(x, hidden)
  File "/home/huyiwen/anaconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/huyiwen/KnowledgeDistillation/models/lstm_mpo.py", line 91, in forward
    h0_t[layer] = self.rnn_cell_list[layer](h0_t[layer - 1][0], h0_t[layer])
  File "/home/huyiwen/anaconda3/lib/python3.10/site-packages/torch/nn/modules/container.py", line 295, in __getitem__
    return self._modules[self._get_abs_string_index(idx)]
  File "/home/huyiwen/anaconda3/lib/python3.10/site-packages/torch/nn/modules/container.py", line 285, in _get_abs_string_index
    raise IndexError('index {} is out of range'.format(idx))
IndexError: index 1 is out of range
